### ISSUE TITLE
[Docs] Cleaning of Codebase Required

### ISSUE THREAD

**Issue by captain-pool** [dshahid380/Algos#1]
The following changes on this repository is requested:

- [x] Remove the compiled binaries from the repository.
- [ ] Add links to the Questions / Jot down the questions in README files.
- [ ] rename the files into something meaningful. provided there's no question along with it, it difficult to understand which code solves which problem.
- [ ] Use `autopep8` for python / `cppcheck` for C++ codes and perform basic linting. The codes are extremely difficult to read.

**Comment by dshahid380** [comment]
Thanks for the suggestion @captain-pool , I will surely do this as soon as possible.
